[[blogs]]

title = "COMP2521 on Easy Mode"
slug = "cs2521-on-easy-mode"
lede = "This blog walks through everything you need to know to get through COMP2521"
tags = ["UNSW"]
md_path = "blogs/2521_easy_mode/2521_easy_mode.md"
img_path = "static/hero_zion.jpg"
published  = 2023-03-28T12:00:00
last_updated = 2023-03-28T12:00:00

[[blogs]]

title = "Prepping for Interviews in Big Tech"
slug = "bigtech-interviews"
lede = "This explores the main pieces of advice I give to students preparing for intern/grad interviews in big tech."
tags = ["Interview Advice"]
md_path = "blogs/interview_advice/blog.md"
img_path = "static/hero_zion.jpg"
published  = 2023-03-28T12:00:00
last_updated = 2023-03-28T12:00:00
